// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinhaSaude.Models;

namespace mysqlMinhaSaude.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211213210157_M00")]
    partial class M00
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("mysqlMinhaSaude.Models.CaixinhaDeRemedios", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int>("nome")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("mysqlcsharpems");
                });
#pragma warning restore 612, 618
        }
    }
}
